wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/pep/Saccharomyces_cerevisiae.R64-1-1.pep.all.fa.gz
wget ftp://ftp.ensembl.org/pub/release-79/gtf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.79.gtf.gz
wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/ncrna/Saccharomyces_cerevisiae.R64-1-1.ncrna.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.I.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.II.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.III.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.IV.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.V.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.VI.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.VII.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.VIII.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.IX.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.X.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.XI.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.XII.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.XIII.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.XIV.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.XV.fa.gz
#wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome.XVI.fa.gz
wget ftp://ftp.ensembl.org/pub/release-79/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz
wget ftp://ftp.ensembl.org/pub/release-79/variation/vcf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae_incl_consequences.vcf.gz
wget ftp://ftp.ensembl.org/pub/release-79/variation/vcf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.vcf.gz
