samtools index HRSV0h-rep1.bam
samtools index HRSV0h-rep2.bam
samtools index HRSV12h-rep1.bam
samtools index HRSV12h-rep2.bam
samtools index HRSV16h-rep1.bam
samtools index HRSV16h-rep2.bam
samtools index HRSV20h-rep1.bam
samtools index HRSV20h-rep2.bam
samtools index HRSV24h-rep1.bam
samtools index HRSV24h-rep2.bam
samtools index HRSV2h-rep1.bam
samtools index HRSV2h-rep2.bam
samtools index HRSV4h-rep1.bam
samtools index HRSV4h-rep2.bam
samtools index HRSV8h-rep1.bam
samtools index HRSV8h-rep2.bam
