htseq-count -f bam -s no HSV4h-Rep1.bam Homo_sapiens.GRCh38.81.gtf > HSV4h-Rep1.count
htseq-count -f bam -s no HSV6h-Rep1.bam Homo_sapiens.GRCh38.81.gtf > HSV6h-Rep1.count
htseq-count -f bam -s no HSV2h-Rep1.bam Homo_sapiens.GRCh38.81.gtf > HSV2h-Rep1.count
htseq-count -f bam -s no HSV8h-Rep1.bam Homo_sapiens.GRCh38.81.gtf > HSV8h-Rep1.count
htseq-count -f bam -s no Mock-Rep2.bam Homo_sapiens.GRCh38.81.gtf > Mock-Rep2.count
htseq-count -f bam -s no HSV8h-Rep2.bam Homo_sapiens.GRCh38.81.gtf > HSV8h-Rep2.count
htseq-count -f bam -s no Mock-Rep1.bam Homo_sapiens.GRCh38.81.gtf > Mock-Rep1.count
htseq-count -f bam -s no HSV2h-Rep2.bam Homo_sapiens.GRCh38.81.gtf > HSV2h-Rep2.count
htseq-count -f bam -s no HSV4h-Rep2.bam Homo_sapiens.GRCh38.81.gtf > HSV4h-Rep2.count
htseq-count -f bam -s no HSV6h-Rep2.bam Homo_sapiens.GRCh38.81.gtf > HSV6h-Rep2.count
