annotate_variation.pl -buildver hg19 GEUVADIS.chr10.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr11.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr12.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr13.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr14.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr15.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr16.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr17.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr18.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr19.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr1.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr20.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr21.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr22.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr2.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr3.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr4.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr5.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr6.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr7.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr8.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
annotate_variation.pl -buildver hg19 GEUVADIS.chr9.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes-Genotype humandb/
