annotate_variation.pl -buildver hg38 HRSV0h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV0h-rep2.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV12h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV12h-rep2.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV16h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV16h-rep2.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV20h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV20h-rep2.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV24h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV24h-rep2.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV2h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV2h-rep2.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV4h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV4h-rep2.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV8h-rep1.flt.anno humandb
annotate_variation.pl -buildver hg38 HRSV8h-rep2.flt.anno humandb
