htseq-count -f bam -s no S7-Mock.bam Homo_sapiens.GRCh38.81.gtf > S7-Mock.count
htseq-count -f bam -s no S8-Mock.bam Homo_sapiens.GRCh38.81.gtf > S8-Mock.count
htseq-count -f bam -s no S2-WNV.bam Homo_sapiens.GRCh38.81.gtf > S2-WNV.count
htseq-count -f bam -s no S6-WNV.bam Homo_sapiens.GRCh38.81.gtf > S6-WNV.count
htseq-count -f bam -s no S10-Mock.bam Homo_sapiens.GRCh38.81.gtf > S10-Mock.count
htseq-count -f bam -s no S10-WNV.bam Homo_sapiens.GRCh38.81.gtf > S10-WNV.count
htseq-count -f bam -s no S9-Mock.bam Homo_sapiens.GRCh38.81.gtf > S9-Mock.count
htseq-count -f bam -s no S6-Mock.bam Homo_sapiens.GRCh38.81.gtf > S6-Mock.count
htseq-count -f bam -s no S3-WNV.bam Homo_sapiens.GRCh38.81.gtf > S3-WNV.count
htseq-count -f bam -s no S7-WNV.bam Homo_sapiens.GRCh38.81.gtf > S7-WNV.count
htseq-count -f bam -s no S1-Mock.bam Homo_sapiens.GRCh38.81.gtf > S1-Mock.count
htseq-count -f bam -s no S2-Mock.bam Homo_sapiens.GRCh38.81.gtf > S2-Mock.count
htseq-count -f bam -s no S5-Mock.bam Homo_sapiens.GRCh38.81.gtf > S5-Mock.count
htseq-count -f bam -s no S9-WNV.bam Homo_sapiens.GRCh38.81.gtf > S9-WNV.count
htseq-count -f bam -s no S1-WNV.bam Homo_sapiens.GRCh38.81.gtf > S1-WNV.count
htseq-count -f bam -s no S5-WNV.bam Homo_sapiens.GRCh38.81.gtf > S5-WNV.count
htseq-count -f bam -s no S4-WNV.bam Homo_sapiens.GRCh38.81.gtf > S4-WNV.count
htseq-count -f bam -s no S8-WNV.bam Homo_sapiens.GRCh38.81.gtf > S8-WNV.count
htseq-count -f bam -s no S3-Mock.bam Homo_sapiens.GRCh38.81.gtf > S3-Mock.count
htseq-count -f bam -s no S4-Mock.bam Homo_sapiens.GRCh38.81.gtf > S4-Mock.count
