sh mTECs-Cov-chr1.sh
sh mTECs-Cov-chr2.sh
sh mTECs-Cov-chr3.sh
sh mTECs-Cov-chr4.sh
sh mTECs-Cov-chr5.sh
sh mTECs-Cov-chr6.sh
sh mTECs-Cov-chr7.sh
sh mTECs-Cov-chr8.sh
sh mTECs-Cov-chr9.sh
sh mTECs-Cov-chr10.sh
sh mTECs-Cov-chr11.sh
sh mTECs-Cov-chr12.sh
sh mTECs-Cov-chr13.sh
sh mTECs-Cov-chr14.sh
sh mTECs-Cov-chr15.sh
sh mTECs-Cov-chr16.sh
sh mTECs-Cov-chr17.sh
sh mTECs-Cov-chr18.sh
sh mTECs-Cov-chr19.sh
sh mTECs-Cov-chrMT.sh
sh mTECs-Cov-chrX.sh
sh mTECs-Cov-chrY.sh
