samtools index Tspan8_negative_MHCII_high_rep1_Mono.bam
samtools index Tspan8_negative_MHCII_high_rep2_Mono.bam
samtools index Tspan8_negative_MHCII_low_rep1_Mono.bam
samtools index Tspan8_negative_MHCII_low_rep2_Mono.bam
samtools index Tspan8_positive_MHCII_high_rep1_Mono.bam
samtools index Tspan8_positive_MHCII_high_rep2_Mono.bam
samtools index Tspan8_positive_MHCII_low_rep1_Mono.bam
samtools index Tspan8_positive_MHCII_low_rep2_Mono.bam
