wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr01.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr02.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr03.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr04.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr05.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr06.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr07.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr08.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr09.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr10.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr11.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr12.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr13.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr14.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr15.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chr16.fsa
wget http://downloads.yeastgenome.org/sequence/S288C_reference/chromosomes/fasta/chrmt.fsa
