convert2annovar.pl -format vcf4 S2-WNV.flt.vcf -outfile S2-WNV.flt.anno
convert2annovar.pl -format vcf4 S8-Mock.flt.vcf -outfile S8-Mock.flt.anno
convert2annovar.pl -format vcf4 S9-Mock.flt.vcf -outfile S9-Mock.flt.anno
convert2annovar.pl -format vcf4 S5-Mock.flt.vcf -outfile S5-Mock.flt.anno
convert2annovar.pl -format vcf4 S4-Mock.flt.vcf -outfile S4-Mock.flt.anno
convert2annovar.pl -format vcf4 S6-Mock.flt.vcf -outfile S6-Mock.flt.anno
convert2annovar.pl -format vcf4 S6-WNV.flt.vcf -outfile S6-WNV.flt.anno
convert2annovar.pl -format vcf4 S9-WNV.flt.vcf -outfile S9-WNV.flt.anno
convert2annovar.pl -format vcf4 S7-Mock.flt.vcf -outfile S7-Mock.flt.anno
convert2annovar.pl -format vcf4 S2-Mock.flt.vcf -outfile S2-Mock.flt.anno
convert2annovar.pl -format vcf4 S3-Mock.flt.vcf -outfile S3-Mock.flt.anno
convert2annovar.pl -format vcf4 S1-Mock.flt.vcf -outfile S1-Mock.flt.anno
convert2annovar.pl -format vcf4 S10-WNV.flt.vcf -outfile S10-WNV.flt.anno
convert2annovar.pl -format vcf4 S4-WNV.flt.vcf -outfile S4-WNV.flt.anno
convert2annovar.pl -format vcf4 S8-WNV.flt.vcf -outfile S8-WNV.flt.anno
convert2annovar.pl -format vcf4 S7-WNV.flt.vcf -outfile S7-WNV.flt.anno
convert2annovar.pl -format vcf4 S5-WNV.flt.vcf -outfile S5-WNV.flt.anno
convert2annovar.pl -format vcf4 S10-Mock.flt.vcf -outfile S10-Mock.flt.anno
convert2annovar.pl -format vcf4 S3-WNV.flt.vcf -outfile S3-WNV.flt.anno
convert2annovar.pl -format vcf4 S1-WNV.flt.vcf -outfile S1-WNV.flt.anno
