annotate_variation.pl -buildver hg38 S10-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S10-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S1-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S1-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S2-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S2-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S3-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S3-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S4-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S4-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S5-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S5-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S6-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S6-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S7-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S7-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S8-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S8-WNV.flt.anno humandb
annotate_variation.pl -buildver hg38 S9-Mock.flt.anno humandb
annotate_variation.pl -buildver hg38 S9-WNV.flt.anno humandb
